export const REQUEST_GOALS = 'REQUEST_GOALS'
export const RECEIVE_GOALS = 'RECEIVE_GOALS'
export const RECEIVE_GOALS_SUCCESS = 'RECEIVE_GOALS_SUCCESS'
export const RECEIVE_GOALS_FAIL = 'RECEIVE_GOALS_FAIL'
